name: buntokmelapor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.11.0
  google_sign_in: 6.0.2
  firebase_auth: 4.2.2
  lottie: 2.3.0
  introduction_screen: 3.1.6
  get_storage: 2.1.1
  cloud_firestore: 4.4.5
  avatar_glow: 2.0.2
  intl: 0.18.0
  image_picker: 0.8.7+4
  firebase_storage: 11.1.2
  flutter_secure_storage: 8.0.0
  flutter_cupertino_settings: 0.5.0
  syncfusion_flutter_charts: 21.2.6
  flutter_local_notifications: 14.1.0
  syncfusion_flutter_pdf: 21.2.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

