name: buntokmelapor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  firebase_auth: ^4.16.0
  lottie: ^3.1.2
  introduction_screen: ^3.1.14
  get_storage: 2.1.1
  cloud_firestore: ^4.14.0
  avatar_glow: ^3.0.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  firebase_storage: ^11.6.0
  flutter_secure_storage: ^9.2.2
  flutter_cupertino_settings: 0.5.0
  syncfusion_flutter_charts: ^26.2.8
  flutter_local_notifications: ^17.2.1+2
  syncfusion_flutter_pdf: ^26.2.8
  firebase_messaging: ^14.6.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

