// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8PAeYA1aIIDtDMAB_Pv6ND-r67etub-o',
    appId: '1:21298091752:web:0049b3c4d2102567841b5d',
    messagingSenderId: '21298091752',
    projectId: 'buntokmelapor',
    authDomain: 'buntokmelapor.firebaseapp.com',
    storageBucket: 'buntokmelapor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVep_HHyeukeXNl4aoxTTbyaedguWCoU0',
    appId: '1:21298091752:android:aeee7514129bf30e841b5d',
    messagingSenderId: '21298091752',
    projectId: 'buntokmelapor',
    storageBucket: 'buntokmelapor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCovWGDtmLVYumcAOCL6ez3HS0tDnfylB0',
    appId: '1:21298091752:ios:737886ae8459e59a841b5d',
    messagingSenderId: '21298091752',
    projectId: 'buntokmelapor',
    storageBucket: 'buntokmelapor.appspot.com',
    androidClientId: '21298091752-8cj59eiviu44prhmgsab6kg90su88b40.apps.googleusercontent.com',
    iosClientId: '21298091752-dfkc0lkfrh3189lqao6ohaio1713p1u0.apps.googleusercontent.com',
    iosBundleId: 'com.briancodex.buntokmelapor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCovWGDtmLVYumcAOCL6ez3HS0tDnfylB0',
    appId: '1:21298091752:ios:737886ae8459e59a841b5d',
    messagingSenderId: '21298091752',
    projectId: 'buntokmelapor',
    storageBucket: 'buntokmelapor.appspot.com',
    androidClientId: '21298091752-8cj59eiviu44prhmgsab6kg90su88b40.apps.googleusercontent.com',
    iosClientId: '21298091752-dfkc0lkfrh3189lqao6ohaio1713p1u0.apps.googleusercontent.com',
    iosBundleId: 'com.briancodex.buntokmelapor',
  );
}
